name: automate-real-data-download

on:
  schedule:
    - cron: '* * * 0 *' # runs every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

          
      - name: execute py script # run sj-gobierno.py to get the latest data
        run: ./venv/Scripts/python.exe ./py/download_real_time.py  