name: real time data collection

on:
  schedule:
    - cron: '*/45 * * * *' # runs every 30 min
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r py/download_requirements.txt
          
      - name: execute py script # run sj-gobierno.py to get the latest data
        env:
          DBNAME: ${{ secrets.DBNAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_HOST: ${{ secrets.DB_HOST }}
          PASSWORD: ${{ secrets.PASSWORD }}
          MONGODB: ${{ secrets.MONGODB}}
        run: python py/download_real_time.py
