name: automate-real-data-download

on:
  # schedule:
  #   - cron: '*/2 * * * *' # runs every hour
  # workflow_dispatch:
    push:
      branches: main
      paths-ignore:
        - '*'
        - '!.github/workflows/main.yml'
        - '!py/download_real_time.py'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run sj-gobierno.py to get the latest data
        run: python ./py/download_real_time.py
