name: model prediction

on:
  schedule:
    - cron: '*/30 * * * *' # runs every 30 min
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5' # install the python version needed
          
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: py/requirements.txt  # this is optional

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

        # the package installation will only be executed when the
        # requirements-files have changed.
      - run: pip install -r py/requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Execute script
        run: python py/Traffic_Prediction.py